// app/privacy/page.tsx
import type { Metadata } from "next";
import { Header } from "../../components/Header";

export const metadata: Metadata = {
  title: "Политика конфиденциальности | Лаборатория тишины",
  description: "Условия обработки данных при отправке заявки на диагностику.",
  alternates: { canonical: "/privacy/" },
};

export default function PrivacyPage() {
  return (
    <main className="legal-page">
      <Header dark={false} />
      <article>
        <p className="eyebrow dark-label">Проект документа</p>
        <h1>Политика конфиденциальности</h1>
        <p className="legal-notice">Перед публичным запуском документ должен быть дополнен реквизитами оператора данных и утверждён ответственным лицом.</p>
        <h2>Какие данные собираются</h2><p>Имя, телефон, необязательный email, ответы о шуме и квартире, а также файлы, которые пользователь прикладывает добровольно.</p>
        <h2>Зачем они нужны</h2><p>Чтобы уточнить ситуацию, подготовиться к контакту и согласовать диагностику объекта в Москве.</p>
        <h2>Как обрабатываются файлы</h2><p>План, фото, видео и аудио используются только как контекст заявки. Запись телефона не считается сертифицированным измерением.</p>
        <h2>Передача третьим сторонам</h2><p>Данные могут передаваться в настроенную CRM для обработки заявки. Рекламной аналитике не передаются телефоны, email, сообщения и имена файлов.</p>
        <h2>Срок и отзыв согласия</h2><p>Срок хранения и рабочий контакт для отзыва согласия будут опубликованы после подтверждения реквизитов оператора.</p>
      </article>
    </main>
  );
}

// apps/engineering/src/routes/privacy/+page.svelte
<svelte:head>
  <title>Политика конфиденциальности — Лаборатория тишины</title>
  <meta name="description" content="Информация об обработке данных в форме диагностики Лаборатории тишины." />
  <meta name="robots" content="noindex,follow" />
  <link rel="canonical" href="/privacy/" />
</svelte:head>

<section class="privacy-page">
  <header><div class="section-label">Юридическая информация</div><h1>Политика конфиденциальности</h1></header>
  <article>
    <p><strong>Рабочая версия.</strong> До публикации владельцу сайта необходимо добавить реквизиты оператора, юридические основания, сроки хранения, перечень обработчиков и актуальные каналы обращения.</p>
    <h2>Какие данные собирает форма</h2><p>Описание шума и помещения, имя, телефон, необязательный email, комментарий и необязательные файлы, которые пользователь прикладывает сам.</p>
    <h2>Для чего нужны данные</h2><p>Чтобы связаться с пользователем, уточнить инженерную задачу и согласовать следующий шаг — выездную диагностику.</p>
    <h2>Файлы</h2><p>План, фотографии, видео и аудио используются только как контекст к обращению. Запись с телефона не заменяет профессиональный замер.</p>
    <h2>Передача и защита</h2><p>Заявка передаётся в настроенную CRM. Конкретный состав получателей и сроки хранения должны быть уточнены оператором до запуска сайта.</p>
    <h2>Отзыв согласия</h2><p>Контакт для запросов субъекта персональных данных должен быть добавлен владельцем сайта до публикации.</p>
  </article>
</section>
